# Generated by Django 5.0.2 on 2025-02-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('cr_number', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties')),
                ('documents', models.FileField(blank=True, null=True, upload_to='properties_docs')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('unavailable', 'غير متاح'), ('under_maintenance', 'تحت الصيانة')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('apartment', 'شقة'), ('office', 'مكتب'), ('shop', 'محل')], max_length=10)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_furnished', models.BooleanField(default=False)),
                ('before_images', models.ImageField(blank=True, null=True, upload_to='units/before/')),
                ('after_images', models.ImageField(blank=True, null=True, upload_to='units/after/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
