# Generated by Django 5.0.2 on 2025-02-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('landlord_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('tenant_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
            ],
        ),
    ]
