# Generated by Django 5.0.3 on 2025-02-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('paid', 'مدفوع'), ('partial', 'جزئي'), ('late', 'متأخر')], default='paid', max_length=10)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='payments/')),
                ('remaining_blance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leases.lease')),
            ],
        ),
    ]
